.TH SYSCALL 1
.SH NAME
syscall \- Test a system call
.SH SYNOPSIS
.B syscall
[\fB\-ovlh\fR]
.IR entry
.IR arg ...
.SH DESCRIPTION
.B syscall(1)
is an effort to port the plan9 syscall command to Linux. Not all the system calls are supposed to work since the system call convention on linux is more complex than plan9 but the most trivial ones are already implemented. Instead of relying on the libc implementation this program uses the 
.B syscall(2)
library function to invoke the system calls.
.SH OPTIONS
.TP
.BR \-o
Output to stdout the contents of the buffer argument specified as buf.
.TP
.BR \-v
Output to stderr the return value of the system call.
.TP
.BR \-l
Print all the available system calls and exit. Note that not all the linux system calls can be invoked using this tool.
.TP
.BR \-h
Print a help message and exit.
.SH EXAMPLES
Write a string to standard output:

	syscall write 1 hello 5

Read a string from the standard input and output the buffer contents to stdout:

	syscall -o read 0 buf 3

Get the pid of the current running process:

	syscall -v getpid

Get the current working directory:

	syscall -ov getcwd buf 100

Create a directory:

	syscall mkdir my-dir 755 

Exit the program with status 2:

	syscall -o exit 2
